AWSTemplateFormatVersion: '2010-09-09'
Description: FridayHITT Outputs

Resources:
  VPCId:
    Description: VPC ID
    Value: !Ref MyVPC

  PublicSubnetIds:
    Description: IDs of the public subnets
    Value: !Join [",", [!Ref PublicSubnet1, !Ref PublicSubnet2]]

  PrivateSubnetIds:
    Description: IDs of the private subnets
    Value: !Join [",", [!Ref PrivateSubnet1, !Ref PrivateSubnet2]]
