AWSTemplateFormatVersion: '2010-09-09'
Description: FridayHITT Route Tables

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID

Resources:
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: PublicRouteTable
        - Key: Environment
          Value: FridayHITT

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn:
      - NatGateway1
      - NatGateway2
    Properties:
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: PrivateRouteTable
        - Key: Environment
          Value: FridayHITT

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGateway
