AWSTemplateFormatVersion: '2010-09-09'
Description: FridayHITT Security Groups

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EC2 instances
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: SecurityGroupEC2
        - Key: Environment
          Value: FridayHITT

  JumpBoxSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Jump Box
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref JumpBoxSSHAllowedIPRange  # Specify the allowed IP range
      Tags:
        - Key: Name
          Value: SecurityGroupJumpBox
        - Key: Environment
          Value: FridayHITT

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EC2 instances in the private subnet
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref JumpBoxSSHAllowedIPRange  # Use the same allowed IP range as JumpBoxSecurityGroup
      Tags:
        - Key: Name
          Value: SecurityGroupEC2Private
        - Key: Environment
          Value: FridayHITT
