AWSTemplateFormatVersion: '2010-09-09'
Description: FridayHITT Subnets

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID

Resources:
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: "10.0.0.0/24"
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet1
        - Key: Environment
          Value: FridayHITT

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: "10.0.1.0/24"
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet2
        - Key: Environment
          Value: FridayHITT

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: "10.0.2.0/24"
      Tags:
        - Key: Name
          Value: PrivateSubnet1
        - Key: Environment
          Value: FridayHITT

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: "10.0.3.0/24"
      Tags:
        - Key: Name
          Value: PrivateSubnet2
        - Key: Environment
          Value: FridayHITT
