AWSTemplateFormatVersion: '2010-09-09'
Description: FridayHITT VPC

Parameters:
  VpcCidrBlock:
    Type: String
    Default: 10.0.0.0/16
    Description: IP address range for the VPC

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      Tags:
        - Key: Name
          Value: FridayHITT VPC
