AWSTemplateFormatVersion: '2010-09-09'
Description: FridayHITT Mini Network with Jump Box, Security Rules, Routing, and NAT Gateway

Parameters:
  VpcCidrBlock:
    Type: String
    Default: 10.0.0.0/16
    Description: IP address range for the VPC

  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Key pair for SSH access

  EC2InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type for public and private instances

  EC2ImageId:
    Type: AWS::EC2::ImageId
    Default: ami-testID
    Description: EC2 Amazon Machine Image (AMI) ID

  JumpBoxSSHAllowedIPRange:
    Type: String
    Description: Allowed IP range for SSH access to the Jump Box
    Default: 0.0.0.0/0
